version: '3.7'

services:
  web:
    image: 8ct8pus/nginx-php-fpm-alpine:latest
    container_name: hstat
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/src
    volumes:
      # development directory
      - ./:/var/www/site/
